Fix/Clean: move of CommandCall to shinken/commandcall requested more attention.
- shinken/__init__ : import explicitely objects.
  prevents of import errors, see below.
- test import fixed.
- schedulerdaemon import cleaned.



Using Pyro 3.9.1
Traceback (most recent call last):
  File "./shinken/bin/shinken-broker", line 51, in <module>
    from shinken.daemons.brokerdaemon import Broker
  File "./shinken/shinken/daemons/brokerdaemon.py", line 40, in <module>
    from shinken.external_command import ExternalCommand
  File "./shinken/shinken/external_command.py", line 33, in <module>
    from shinken.pollerlink import PollerLink
  File "./shinken/shinken/pollerlink.py", line 27, in <module>
    from shinken.satellitelink import SatelliteLink, SatelliteLinks
  File "./shinken/shinken/satellitelink.py", line 32, in <module>
    from shinken.objects import Item, Items
  File "./shinken/shinken/objects/__init__.py", line 45, in <module>
    from config import Config
  File "./shinken/shinken/objects/config.py", line 41, in <module>
    from shinken.arbiterlink import ArbiterLink, ArbiterLinks
  File "./shinken/shinken/arbiterlink.py", line 25, in <module>
    from shinken.satellitelink import SatelliteLink, SatelliteLinks
ImportError: cannot import name SatelliteLink