Test: services: fix non-deterministic assert.
From time to time the previous assert failed (see below) because:

 svc.last_hard_state_change is equal to 'now+1'

because scheduler_loop() work load is spread over 2 seconds.

Now make sure that svc.last_hard_state_change is really changed.

From: https://travis-ci.org/gst/shinken/jobs/46895695 :

test_service_last_hard_state (test_services.TestService) ... FAIL
======================================================================
FAIL: test_service_last_hard_state (test_services.TestService)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/gst/shinken/test/test_services.py", line 200, in test_service_last_hard_state
    self.assertEqual(now, svc.last_hard_state_change)
AssertionError: 1421178531 != 1421178532