Fix: missed a % qualifier in format string for a logger.debug() call
Seen while executing a test (see below traceback),
though strangely cause couldn't reproduce it after (debug seemed always disabled in logger call).

Anyway, the tracebacks never lie :)

======================================================================
ERROR: test_dummy (test_macromodulations.TestMacroModulations)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gstarck/work/work/SFL/Supervision/shinken/test/test_macromodulations.py", line 31, in setUp
    self.setup_with_file('etc/shinken_macromodulations.cfg')
  File "/home/gstarck/work/work/SFL/Supervision/shinken/test/shinken_test.py", line 232, in setup_with_file
    self.conf.prepare_for_sending()
  File "/home/gstarck/work/work/SFL/Supervision/shinken/shinken/objects/config.py", line 936, in prepare_for_sending
    logger.debug("[config] time to serialize the global conf : %s (size:%)", time.time() - t0, len(whole_conf_pack))
  File "/home/gstarck/work/work/SFL/Supervision/shinken/shinken/log.py", line 214, in debug
    logging.Logger.debug(self, *args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1140, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1271, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1281, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1321, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 749, in handle
    self.emit(record)
  File "/usr/local/lib/python2.7/dist-packages/nose/plugins/logcapture.py", line 82, in emit
    self.buffer.append(self.format(record))
  File "/usr/lib/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
ValueError: unsupported format character ')' (0x29) at index 55
-------------------- >> begin captured stdout << ---------------------